// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Matěj Uchytil",
            "url": "https://github.com/uchytma/go-example-rest-api"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/math/greatest-common-divisor": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/math"
                ],
                "summary": "Return greater common divisor (GCD) of specified numbers.",
                "operationId": "math/greatest-common-divisor",
                "parameters": [
                    {
                        "description": "All numbers must be greater than zero.",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        },
        "/math/least-common-multiple": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "/math"
                ],
                "summary": "Return least common multiple (LCM) of specified numbers.",
                "operationId": "math/least-common-multiple",
                "parameters": [
                    {
                        "description": "All numbers must be greater than zero.",
                        "name": "model",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Example REST API",
	Description:      "Example of rest API written in Golang, used for learning purposes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
