info:
  contact:
    name: Matěj Uchytil
    url: https://github.com/uchytma/go-example-rest-api
  description: Example of rest API written in Golang, used for learning purposes.
  title: Example REST API
  version: "1.0"
paths:
  /math/greatest-common-divisor:
    post:
      operationId: math/greatest-common-divisor
      parameters:
      - description: bottle info
        in: body
        name: bottles
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: All numbers must be integers greater than zero.
      tags:
      - /math
swagger: "2.0"
